name: Build and store YASM Frontend Image

on:
  push:
    branches:
      - task/**
      - feature/**
      - bug/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - closed

jobs:
  build_push_image:
    name: Building and storing YASM Frontend Docker Image
    uses: necro-cloud/automations/.github/workflows/build-docker-image.yml@main
    with:
      dev_version_name: development
      image_name: frontend
      image_proper_name: YASM Frontend
      build_path: .
      repository: yasm
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
